# CMake generated Testfile for 
# Source directory: /home/rip-acer-vn7-591g-1/catkin_ws/src/rosserial/rosserial_test
# Build directory: /home/rip-acer-vn7-591g-1/catkin_ws/build_cb/rosserial_test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_rosserial_test_rostest_test_rosserial_server_socket.test "/home/rip-acer-vn7-591g-1/catkin_ws/build_cb/rosserial_test/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/rip-acer-vn7-591g-1/catkin_ws/build_cb/rosserial_test/test_results/rosserial_test/rostest-test_rosserial_server_socket.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/rip-acer-vn7-591g-1/catkin_ws/src/rosserial/rosserial_test --package=rosserial_test --results-filename test_rosserial_server_socket.xml --results-base-dir \"/home/rip-acer-vn7-591g-1/catkin_ws/build_cb/rosserial_test/test_results\" /home/rip-acer-vn7-591g-1/catkin_ws/src/rosserial/rosserial_test/test/rosserial_server_socket.test ")
add_test(_ctest_rosserial_test_rostest_test_rosserial_server_serial.test "/home/rip-acer-vn7-591g-1/catkin_ws/build_cb/rosserial_test/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/rip-acer-vn7-591g-1/catkin_ws/build_cb/rosserial_test/test_results/rosserial_test/rostest-test_rosserial_server_serial.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/rip-acer-vn7-591g-1/catkin_ws/src/rosserial/rosserial_test --package=rosserial_test --results-filename test_rosserial_server_serial.xml --results-base-dir \"/home/rip-acer-vn7-591g-1/catkin_ws/build_cb/rosserial_test/test_results\" /home/rip-acer-vn7-591g-1/catkin_ws/src/rosserial/rosserial_test/test/rosserial_server_serial.test ")
add_test(_ctest_rosserial_test_rostest_test_rosserial_python_socket.test "/home/rip-acer-vn7-591g-1/catkin_ws/build_cb/rosserial_test/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/rip-acer-vn7-591g-1/catkin_ws/build_cb/rosserial_test/test_results/rosserial_test/rostest-test_rosserial_python_socket.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/rip-acer-vn7-591g-1/catkin_ws/src/rosserial/rosserial_test --package=rosserial_test --results-filename test_rosserial_python_socket.xml --results-base-dir \"/home/rip-acer-vn7-591g-1/catkin_ws/build_cb/rosserial_test/test_results\" /home/rip-acer-vn7-591g-1/catkin_ws/src/rosserial/rosserial_test/test/rosserial_python_socket.test ")
subdirs(gtest)
